version: "3"
services:
  api:
    build:
      context: ./Monitor.API
      dockerfile: Dockerfile
      args:
        version: 1
    image: monitor.api
    ports:
      - 8080:8080
    networks:
      - monitor_api_network
  prometheus:
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitor_api_network
    volumes:
      - './prometheus/data:/data'
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitor_api_network
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - monitor_api_network

networks:
  monitor_api_network:
    driver: overlay
    attachable: true
