global:
  scrape_interval: 5s
  scrape_timeout: 5s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: "monitor-api-job"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]




